SELECT 
DATE_FORMAT(O.SALES_DATE, '%Y') AS 'YEAR',
DATE_FORMAT(O.SALES_DATE, '%c') AS 'MONTH',
COUNT(DISTINCT U.USER_ID) AS 'PURCHASED_USERS', 

ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*)
    FROM USER_INFO AS U 
    WHERE U.JOINED >= '2021-01-01' AND U.JOINED < '2022-01-01'
), 1) AS 'PURCHASED_RATIO'

FROM USER_INFO AS U 
JOIN ONLINE_SALE AS O ON O.USER_ID = U.USER_ID
WHERE U.JOINED >= '2021-01-01' AND U.JOINED < '2022-01-01'
GROUP BY DATE_FORMAT(O.SALES_DATE, '%Y'), DATE_FORMAT(O.SALES_DATE, '%m')
